spring:
  zipkin:
    base-url: http://zipkin-service:9411/
    # base-url: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: rabbit-service
    # host: localhost
    # port: 15672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
info:
  author: Joel Jerrys M Farias
  mail: joeljerrys95@gmail.com
server:
  port: ${PORT:9999}
message: Mensagem generica

queue:
  serie-service: queue-serie-service
  movie-service: queue-movie-service
  movieCatalog-service: queue-catalogMovie-service
  serieCatalog-service: queue-catalogSerie-service


## Resilience4J configs for CircuitBreaker Pattern
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCalssInHalfOpenState: 2
        automaticTransitionFromOpenToHalfIfOpenEnabled: true




